### ISSUE TITLE
Lack of Swap and Liquidity Features in Dymension Portal App

### ISSUE THREAD

**Issue by toglok** [dymensionxyz/networks#299]
During the testnet phase, I observed that the swap and liquidity features are absent in the Dymension portal app. While community involvement is appreciated, this deficiency could pose a significant challenge upon the mainnet launch.

I found that, despite the enticing ability to create rollaps with Dimensi, the need for swap and liquidity features with DYM pairing is crucial for establishing a robust token economy.

I recommend promptly integrating swap and liquidity features into the Dymension portal app. This would not only enhance user convenience but also contribute to the formation of a stronger token economy. Enabling users to easily create LP with DYM will help reinforce the overall value of the token ecosystem.

Thank you for your attention to this report, and I hope updates are implemented soon to enhance the functionality of the Dymension portal app.

**Comment by shaolin-flow** [comment]
Liquidity added 

closing issue

**Comment by toglok** [comment]
tanks
